## True Beacon Assignment

>Manas Baviskar

### Importing Relevant libraries

In [1]:
import pandas as pd
import numpy as np
from datetime import timedelta, date
import datetime as datetime
from dateutil.relativedelta import relativedelta
from dateutil import rrule
import undetected_chromedriver as uc
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import warnings
import math
import timeit
%matplotlib inline
warnings.filterwarnings('ignore')

C:\Users\MANAS\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\MANAS\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\MANAS\anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

### Extracting/Formatting the CSV files

In [2]:
index_df = pd.read_csv("Index_Subset.csv")
scores_df = pd.read_csv("Scores_Subset.csv")
scores_df['Unnamed: 0'] = pd.to_datetime(scores_df['Unnamed: 0'], format = '%Y-%m-%d')
scores_df = scores_df.set_index('Unnamed: 0')
scores_df.index  = scores_df.index.strftime("%d-%m-20%y")
index_df = index_df.set_index('Unnamed: 0')

cols = []
for i in scores_df.columns:
    #scores_df[i] = i
    cols.append(i)
    
a = scores_df.copy()

In [3]:
index_df

,0,1,2,3,4,5,6,7,8,9,...,191,192,193,194,195,196,197,198,199,200
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
02-01-2012,1958850D IS Equity,63MOONS IS Equity,ABB IS Equity,ABNL IS Equity,ACC IS Equity,ACEM IS Equity,ADANI IS Equity,ADE IS Equity,ADSEZ IS Equity,AL IS Equity,...,VCLF IS Equity,VEDL IS Equity,VJYBK IS Equity,VOLT IS Equity,WLCO IS Equity,WPRO IS Equity,YES IS Equity,Z IS Equity,ZYDUSLIF IS Equity,NaN
03-01-2012,1958850D IS Equity,63MOONS IS Equity,ABB IS Equity,ABNL IS Equity,ACC IS Equity,ACEM IS Equity,ADANI IS Equity,ADE IS Equity,ADSEZ IS Equity,AL IS Equity,...,VCLF IS Equity,VEDL IS Equity,VJYBK IS Equity,VOLT IS Equity,WLCO IS Equity,WPRO IS Equity,YES IS Equity,Z IS Equity,ZYDUSLIF IS Equity,NaN
04-01-2012,1958850D IS Equity,63MOONS IS Equity,ABB IS Equity,ABNL IS Equity,ACC IS Equity,ACEM IS Equity,ADANI IS Equity,ADE IS Equity,ADSEZ IS Equity,AL IS Equity,...,VCLF IS Equity,VEDL IS Equity,VJYBK IS Equity,VOLT IS Equity,WLCO IS Equity,WPRO IS Equity,YES IS Equity,Z IS Equity,ZYDUSLIF IS Equity,NaN
05-01-2012,1958850D IS Equity,63MOONS IS Equity,ABB IS Equity,ABNL IS Equity,ACC IS Equity,ACEM IS Equity,ADANI IS Equity,ADE IS Equity,ADSEZ IS Equity,AL IS Equity,...,VCLF IS Equity,VEDL IS Equity,VJYBK IS Equity,VOLT IS Equity,WLCO IS Equity,WPRO IS Equity,YES IS Equity,Z IS Equity,ZYDUSLIF IS Equity,NaN
06-01-2012,1958850D IS Equity,63MOONS IS Equity,ABB IS Equity,ABNL IS Equity,ACC IS Equity,ACEM IS Equity,ADANI IS Equity,ADE IS Equity,ADSEZ IS Equity,AL IS Equity,...,VCLF IS Equity,VEDL IS Equity,VJYBK IS Equity,VOLT IS Equity,WLCO IS Equity,WPRO IS Equity,YES IS Equity,Z IS Equity,ZYDUSLIF IS Equity,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18-03-2020,ABCAP IS Equity,ABFRL IS Equity,ACC IS Equity,ACEM IS Equity,ADANI IS Equity,ADSEZ IS Equity,AJP IS Equity,AL IS Equity,ALKEM IS Equity,AMRJ IS Equity,...,VARROC IS Equity,VBL IS Equity,VEDL IS Equity,VGRD IS Equity,VOLT IS Equity,WHIRL IS Equity,WPRO IS Equity,YES IS Equity,Z IS Equity,ZYDUSLIF IS Equity
19-03-2020,ABCAP IS Equity,ABFRL IS Equity,ACC IS Equity,ACEM IS Equity,ADANI IS Equity,ADSEZ IS Equity,AJP IS Equity,AL IS Equity,ALKEM IS Equity,AMRJ IS Equity,...,VARROC IS Equity,VBL IS Equity,VEDL IS Equity,VGRD IS Equity,VOLT IS Equity,WHIRL IS Equity,WPRO IS Equity,YES IS Equity,Z IS Equity,ZYDUSLIF IS Equity
20-03-2020,ABCAP IS Equity,ABFRL IS Equity,ACC IS Equity,ACEM IS Equity,ADANI IS Equity,ADSEZ IS Equity,AJP IS Equity,AL IS Equity,ALKEM IS Equity,AMRJ IS Equity,...,VARROC IS Equity,VBL IS Equity,VEDL IS Equity,VGRD IS Equity,VOLT IS Equity,WHIRL IS Equity,WPRO IS Equity,YES IS Equity,Z IS Equity,ZYDUSLIF IS Equity
23-03-2020,ABCAP IS Equity,ABFRL IS Equity,ACC IS Equity,ACEM IS Equity,ADANI IS Equity,ADSEZ IS Equity,AJP IS Equity,AL IS Equity,ALKEM IS Equity,AMRJ IS Equity,...,VARROC IS Equity,VBL IS Equity,VEDL IS Equity,VGRD IS Equity,VOLT IS Equity,WHIRL IS Equity,WPRO IS Equity,YES IS Equity,Z IS Equity,ZYDUSLIF IS Equity
24-03-2020,ABCAP IS Equity,ABFRL IS Equity,ACC IS Equity,ACEM IS Equity,ADANI IS Equity,ADSEZ IS Equity,AJP IS Equity,AL IS Equity,ALKEM IS Equity,AMRJ IS Equity,...,VARROC IS Equity,VBL IS Equity,VEDL IS Equity,VGRD IS Equity,VOLT IS Equity,WHIRL IS Equity,WPRO IS Equity,YES IS Equity,Z IS Equity,ZYDUSLIF IS Equity

### Creating a hashcode for each symbol in score column

In [4]:
hashcode = {}
for c,i in enumerate(cols):
    hashcode[i] = c+1

In [5]:
for i in index_df.columns:
    index_df[i]=index_df[i].map(hashcode)

In [6]:
#Since we need top 200 symbols, we drop the redundant column i.e the last one
index_df = index_df.drop(['200'], axis = 1)

In [7]:
index_df = index_df.fillna(0)
for i in index_df.columns:
    index_df[i]=index_df[i].astype(int)

In [8]:
index_df

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
02-01-2012,1,2,3,6,7,8,9,12,13,16,...,356,360,361,363,365,368,371,372,373,375
03-01-2012,1,2,3,6,7,8,9,12,13,16,...,356,360,361,363,365,368,371,372,373,375
04-01-2012,1,2,3,6,7,8,9,12,13,16,...,356,360,361,363,365,368,371,372,373,375
05-01-2012,1,2,3,6,7,8,9,12,13,16,...,356,360,361,363,365,368,371,372,373,375
06-01-2012,1,2,3,6,7,8,9,12,13,16,...,356,360,361,363,365,368,371,372,373,375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18-03-2020,4,5,7,8,9,13,15,16,18,20,...,356,357,359,361,362,365,367,371,372,373
19-03-2020,4,5,7,8,9,13,15,16,18,20,...,356,357,359,361,362,365,367,371,372,373
20-03-2020,4,5,7,8,9,13,15,16,18,20,...,356,357,359,361,362,365,367,371,372,373
23-03-2020,4,5,7,8,9,13,15,16,18,20,...,356,357,359,361,362,365,367,371,372,373
24-03-2020,4,5,7,8,9,13,15,16,18,20,...,356,357,359,361,362,365,367,371,372,373

In [10]:
%%timeit
for days in range(index_df.shape[0]):
    for i in range(index_df.shape[1]):
        if np.isnan(index_df.iloc[days,i]):
            continue
        else:
            a.iloc[days, int(index_df.iloc[days,i]-1)] = 1

34.3 s ± 178 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

### Output

In [11]:
a

,1958850D IS Equity,63MOONS IS Equity,ABB IS Equity,ABCAP IS Equity,ABFRL IS Equity,ABNL IS Equity,ACC IS Equity,ACEM IS Equity,ADANI IS Equity,ADANIGR IS Equity,...,VYSB IS Equity,WHIRL IS Equity,WLCO IS Equity,WLSI IS Equity,WPL IS Equity,WPRO IS Equity,YES IS Equity,Z IS Equity,ZOMATO IS Equity,ZYDUSLIF IS Equity
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
02-01-2012,1.0,1.0,1.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,1.0,1.0,NaN,1.0
03-01-2012,1.0,1.0,1.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,1.0,1.0,NaN,1.0
04-01-2012,1.0,1.0,1.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,1.0,1.0,NaN,1.0
05-01-2012,1.0,1.0,1.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,1.0,1.0,NaN,1.0
06-01-2012,1.0,1.0,1.0,NaN,NaN,1.0,1.0,1.0,1.0,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,1.0,1.0,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18-03-2020,NaN,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,NaN,...,NaN,1.0,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN
19-03-2020,NaN,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,NaN,...,NaN,1.0,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN
20-03-2020,NaN,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,NaN,...,NaN,1.0,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN
23-03-2020,NaN,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,NaN,...,NaN,1.0,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN
24-03-2020,NaN,NaN,NaN,1.0,1.0,NaN,1.0,1.0,1.0,NaN,...,NaN,1.0,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN